import { createServer, IncomingMessage, ServerResponse } from 'http';

export type TradeStatus = 'SUCCESS' | 'FAILED' | 'PENDING';
export type TradeType = 'BUY' | 'SELL' | 'SNIPE';
export interface TradeRecord { id: string; timestamp: string; type: TradeType; token: string; amount: number; price: number; txHash: string | null; status: TradeStatus; pnl: number; }
export interface TelemetryState { wallet?: string; activeTarget: string; buyMode: boolean; executionMode: 'mock' | 'live'; status: 'ONLINE' | 'MOCK' | 'IDLE' | 'UNFUNDED'; totalTrades: number; successfulTrades: number; failedTrades: number; volumeXRP: number; pnlXRP: number; trades: TradeRecord[]; }

export const telemetry: TelemetryState = { wallet: process.env.WALLET_ADDRESS || process.env.XRPL_WALLET_ADDRESS, activeTarget: '', buyMode: false, executionMode: 'live', status: 'IDLE', totalTrades: 0, successfulTrades: 0, failedTrades: 0, volumeXRP: 0, pnlXRP: 0, trades: [] };
export function setExecutionMode(mode: 'mock' | 'live') { telemetry.executionMode = mode; if (mode === 'mock') telemetry.status = process.env.WALLET_SEED ? 'MOCK' : 'UNFUNDED'; }
export function recordTrade(trade: Omit<TradeRecord, 'id' | 'timestamp'>): TradeRecord { const item = { ...trade, id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`, timestamp: new Date().toISOString() }; telemetry.trades.unshift(item); telemetry.trades = telemetry.trades.slice(0, 100); telemetry.totalTrades++; if (trade.status === 'SUCCESS') telemetry.successfulTrades++; if (trade.status === 'FAILED') telemetry.failedTrades++; telemetry.volumeXRP += Math.abs(trade.amount * trade.price); telemetry.pnlXRP += trade.pnl || 0; return item; }
function send(res: ServerResponse, value: unknown, code = 200) { res.writeHead(code, { 'content-type': 'application/json', 'access-control-allow-origin': '*' }); res.end(JSON.stringify(value)); }
async function body(req: IncomingMessage) { let data = ''; for await (const chunk of req) data += chunk; return JSON.parse(data || '{}'); }
export function startTelemetryServer(port = Number(process.env.PORT) || 3001) { const server = createServer(async (req, res) => { try { if (req.method === 'OPTIONS') return send(res, {}, 204); if (req.method === 'GET' && (req.url === '/' || req.url === '/health')) return send(res, { status: 'ok' }); if (req.method === 'POST' && req.url === '/api/c2/buy-mode') { const value = await body(req); if (typeof value.buyMode !== 'boolean') return send(res, { success: false, error: 'buyMode must be boolean' }, 400); telemetry.buyMode = value.buyMode; return send(res, { success: true, buyMode: telemetry.buyMode }); } if (req.method === 'POST' && req.url === '/api/c2/target') { const value = await body(req); if (typeof value.target !== 'string') return send(res, { success: false, error: 'target must be string' }, 400); telemetry.activeTarget = value.target.trim(); return send(res, { success: true, target: telemetry.activeTarget }); } if (req.method === 'GET' && req.url === '/api/status') return send(res, { status: telemetry.status, executionMode: telemetry.executionMode, buyMode: telemetry.buyMode, activeTarget: telemetry.activeTarget, wallet: telemetry.wallet || 'SIMULATED', uptime: Math.floor(process.uptime()), lastHeartbeat: new Date().toISOString(), stats: { totalTrades: telemetry.totalTrades, successfulTrades: telemetry.successfulTrades, failedTrades: telemetry.failedTrades, volumeXRP: telemetry.volumeXRP, pnlXRP: telemetry.pnlXRP } }); if (req.method === 'GET' && req.url === '/api/trades') return send(res, telemetry.trades); return send(res, { error: 'Not found' }, 404); } catch (error) { return send(res, { success: false, error: error instanceof Error ? error.message : 'Request failed' }, 400); } }); server.listen(port, '0.0.0.0', () => console.log(`Telemetry API listening on ${port}`)); return server; }
