import { createServer, IncomingMessage, ServerResponse } from 'http';
export type TradeStatus='SUCCESS'|'FAILED'|'PENDING'; export type TradeType='BUY'|'SELL'|'SNIPE';
export interface TradeRecord{id:string;timestamp:string;type:TradeType;token:string;amount:number;price:number;txHash:string|null;status:TradeStatus;pnl:number;}
export interface TelemetryState{wallet?:string;activeTarget:string;buyMode:boolean;executionMode:'mock'|'live';status:'ONLINE'|'MOCK'|'IDLE'|'UNFUNDED';totalTrades:number;successfulTrades:number;failedTrades:number;volumeXRP:number;pnlXRP:number;trades:TradeRecord[];}
export const telemetry:TelemetryState={wallet:process.env.WALLET_ADDRESS||process.env.XRPL_WALLET_ADDRESS,activeTarget:'',buyMode:false,executionMode:'mock',status:'IDLE',totalTrades:0,successfulTrades:0,failedTrades:0,volumeXRP:0,pnlXRP:0,trades:[]};
let started=Date.now(); export function setExecutionMode(mode:'mock'|'live'){telemetry.executionMode=mode;telemetry.status=mode==='mock'?(process.env.WALLET_SEED?'MOCK':'UNFUNDED'):'ONLINE';}
export function recordTrade(trade:Omit<TradeRecord,'id'|'timestamp'>){const item={...trade,id:`${Date.now()}-${Math.random().toString(36).slice(2,8)}`,timestamp:new Date().toISOString()};telemetry.trades.unshift(item);telemetry.trades=telemetry.trades.slice(0,100);telemetry.totalTrades++;if(item.status==='SUCCESS')telemetry.successfulTrades++;if(item.status==='FAILED')telemetry.failedTrades++;telemetry.volumeXRP+=Math.abs(item.amount*item.price);telemetry.pnlXRP+=item.pnl||0;return item;}
function send(res:ServerResponse,value:unknown,code=200){res.writeHead(code,{'content-type':'application/json','access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,authorization'});res.end(JSON.stringify(value));}
async function body(req:IncomingMessage){let data='';for await(const chunk of req)data+=chunk;return JSON.parse(data||'{}');}
function snapshot(){return {status:telemetry.status,executionMode:telemetry.executionMode,buyMode:telemetry.buyMode,targetToken:telemetry.activeTarget,activeTarget:telemetry.activeTarget,wallet:telemetry.wallet||'SIMULATED',uptime:Math.floor((Date.now()-started)/1000),lastHeartbeat:new Date().toISOString(),activeHoldings:[],stats:{totalTrades:telemetry.totalTrades,successfulTrades:telemetry.successfulTrades,failedTrades:telemetry.failedTrades,volumeXRP:telemetry.volumeXRP,pnlXRP:telemetry.pnlXRP}};}
export function startTelemetryServer(port=Number(process.env.PORT)||3001){const server=createServer(async(req,res)=>{try{if(req.method==='OPTIONS')return send(res,{},204);const url=(req.url||'').split('?')[0];if(req.method==='GET'&&(url==='/'||url==='/health'))return send(res,{status:'ok'});if(req.method==='GET'&&(url==='/api/status'||url==='/api/telemetry'))return send(res,snapshot());if(req.method==='GET'&&url==='/api/trades')return send(res,telemetry.trades);if((req.method==='POST'||req.method==='GET')&&url==='/api/c2'){const value=req.method==='POST'?await body(req):Object.fromEntries(new URL(req.url||'',`http://${req.headers.host||'localhost'}`).searchParams);const raw=String(value.command||value.message||'').trim();const cmd=raw.toUpperCase();if(!cmd)return send(res,{success:false,error:'command required'},400);const mode=cmd.match(/^(?:SET_MODE|MODE)\s*[:=]?\s*(MOCK|DRY[_ -]?RUN|LIVE)$/);const target=cmd.match(/^(?:TARGET|SET_TARGET)\s*[:=]?\s*(.+)$/);if(cmd==='ARM'||cmd==='BUY MODE: ARMED'||cmd==='BUY_MODE ARMED')telemetry.buyMode=true;else if(cmd==='DISARM'||cmd==='BUY MODE: DISARMED'||cmd==='BUY_MODE DISARMED')telemetry.buyMode=false;else if(mode)setExecutionMode(mode[1].replace(/[-_ ]/g,'')==='LIVE'?'live':'mock');else if(target)telemetry.activeTarget=target[1].trim();else if(/^(?:SNIPE|BUY|SELL)\b/.test(cmd)&&telemetry.executionMode==='mock'){const parts=cmd.split(/\s+/);recordTrade({type:(parts[0]==='BUY'?'BUY':parts[0]==='SELL'?'SELL':'SNIPE'),token:telemetry.activeTarget||parts[1]||'XRP',amount:Number(parts[2])||0,price:Number(parts[3])||0,txHash:null,status:'SUCCESS',pnl:0});}else if(!['STATUS','SITREP'].includes(cmd))return send(res,{success:false,error:`unsupported command: ${raw}`},400);return send(res,{success:true,command:raw,state:snapshot(),trades:telemetry.trades.slice(0,10)});}return send(res,{error:'Not found'},404);}catch(error){return send(res,{success:false,error:error instanceof Error?error.message:'Request failed'},400);}});server.listen(port,'0.0.0.0',()=>console.log(`Telemetry API listening on ${port}`));return server;}
